import type { Metadata } from "next";
import { Marhey } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const marhey = Marhey({
  variable: "--font-marhey",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${marhey.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}